# Generated by Django 4.2.4 on 2023-09-18 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('availability', models.BooleanField(default=True, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'db_table': 'calendario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('forOlder', models.BooleanField(verbose_name='Para mayores')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar del evento')),
                ('date', models.DateTimeField(verbose_name='Fecha del evento')),
                ('cost', models.FloatField(verbose_name='Costo del evento')),
                ('guests', models.PositiveIntegerField(verbose_name='Cantidad de invitados')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de entrada')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Cantidad de producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar de la reserva')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de reserva')),
                ('start_time', models.DateTimeField(verbose_name='Hora de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora de finalización')),
                ('cost', models.FloatField(verbose_name='Costo de la reserva')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.calendar')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('players_num', models.PositiveIntegerField(default=0, verbose_name='Número de jugadores')),
                ('avatar', models.ImageField(default='group.png', upload_to='team_avatar/', verbose_name='Avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('number_teams', models.PositiveIntegerField(default=16, verbose_name='Cantidad de equipos')),
                ('registered_teams', models.PositiveIntegerField(default=0, verbose_name='Equipos registrados')),
                ('date', models.DateTimeField(verbose_name='Fecha del torneo')),
                ('prize_payment', models.FloatField(verbose_name='Pago de premio')),
                ('registration_cost', models.FloatField(verbose_name='Costo de inscripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'db_table': 'torneo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_for', models.IntegerField(verbose_name='Goles a favor')),
                ('goals_against', models.IntegerField(verbose_name='Goles en contra')),
                ('goals_diff', models.IntegerField(verbose_name='Diferencia de goles')),
                ('games_tied', models.IntegerField(verbose_name='Partidos empatados')),
                ('games_won', models.IntegerField(verbose_name='Partidos ganados')),
                ('games_lost', models.IntegerField(verbose_name='Partidos perdidos')),
                ('games_played', models.IntegerField(verbose_name='Partidos jugados')),
                ('score', models.IntegerField(verbose_name='Puntaje')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'verbose_name': 'Torneo y equipo',
                'verbose_name_plural': 'Torneos y equipos',
                'db_table': 'torneo_equipo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='team',
            field=models.ManyToManyField(through='core.TournamentTeam', to='core.team'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(verbose_name='Costo total')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Tipo de pago')),
                ('status', models.CharField(max_length=50, verbose_name='Estado de venta')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de venta')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Cantidad de productos comprados')),
                ('event', models.ManyToManyField(to='core.event', verbose_name='Venta_evento')),
                ('inventory', models.ManyToManyField(to='core.inventory')),
                ('reservation', models.ManyToManyField(to='core.reservation', verbose_name='Venta_reserva')),
                ('tournament', models.ManyToManyField(to='core.tournament', verbose_name='Venta_torneo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cost', models.FloatField(verbose_name='Costo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='Imágen')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dorsal', models.PositiveBigIntegerField(verbose_name='Número de dorsal')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('gender', models.CharField(max_length=50, verbose_name='Género')),
                ('position', models.CharField(max_length=60, verbose_name='Posición')),
                ('yellow_card', models.IntegerField(default=0, verbose_name='Tarjeta amarilla')),
                ('blue_card', models.IntegerField(default=0, verbose_name='Tarjeta azul')),
                ('red_card', models.IntegerField(default=0, verbose_name='Tarjeta roja')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de salida')),
                ('product_quantity_out', models.PositiveIntegerField(verbose_name='Cantidad de productos fuera')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salida',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Puntuación')),
                ('text', models.TextField(verbose_name='Texto')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
                'ordering': ['id'],
            },
        ),
    ]
