# Generated by Django 4.2.4 on 2023-08-28 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('forOlder', models.BooleanField(verbose_name='Para mayores')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de entrada')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Cantidad de producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(verbose_name='Costo total')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Tipo de pago')),
                ('discount', models.BooleanField(verbose_name='Aplica descuento')),
                ('total_discount', models.FloatField(verbose_name='Total descuento')),
                ('status', models.CharField(max_length=50, verbose_name='Estado de venta')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de venta')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Cantidad de productos comprados')),
                ('inventory', models.ManyToManyField(to='core.inventory')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cost', models.FloatField(verbose_name='Costo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='Imágen')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de salida')),
                ('product_quantity_out', models.PositiveIntegerField(verbose_name='Cantidad de productos fuera')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salida',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
