# Generated by Django 4.2.4 on 2023-09-21 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saletournament',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
        migrations.AddField(
            model_name='saletournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
        migrations.AddField(
            model_name='salereservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservation'),
        ),
        migrations.AddField(
            model_name='salereservation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
        migrations.AddField(
            model_name='saleinventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AddField(
            model_name='saleinventory',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='event',
            field=models.ManyToManyField(through='core.SaleEvent', to='core.event'),
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory',
            field=models.ManyToManyField(through='core.SaleInventory', to='core.inventory'),
        ),
        migrations.AddField(
            model_name='sale',
            name='reservation',
            field=models.ManyToManyField(through='core.SaleReservation', to='core.reservation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tournament',
            field=models.ManyToManyField(through='core.SaleTournament', to='core.tournament'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AddField(
            model_name='output',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
