# Generated by Django 4.2.4 on 2023-09-23 15:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(validators=[core.models.validate_today], verbose_name='Fecha del día'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de invitados'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, validators=[core.models.validate_positive], verbose_name='Cantidad de producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(validators=[core.models.validate_positive], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cost',
            field=models.FloatField(validators=[core.models.validate_positive], verbose_name='Costo de inscripción'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(validators=[core.models.validate_date_with_2_days], verbose_name='Fecha de inicio del torneo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Campeonato', max_length=15, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_payment',
            field=models.FloatField(validators=[core.models.validate_positive], verbose_name='Pago de premio'),
        ),
    ]
