# Generated by Django 4.2.4 on 2023-09-23 16:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_calendar_date_alter_event_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.FloatField(validators=[core.models.validate_positive], verbose_name='Costo del evento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product.png', upload_to='product/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.FloatField(validators=[core.models.validate_positive], verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='games_lost',
            field=models.PositiveIntegerField(default=0, verbose_name='Partidos perdidos'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='games_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Partidos jugados'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='games_tied',
            field=models.PositiveIntegerField(default=0, verbose_name='Partidos empatados'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='games_won',
            field=models.PositiveIntegerField(default=0, verbose_name='Partidos ganados'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='goals_against',
            field=models.PositiveIntegerField(default=0, verbose_name='Goles en contra'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='goals_diff',
            field=models.PositiveIntegerField(default=0, verbose_name='Diferencia de goles'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='goals_for',
            field=models.PositiveIntegerField(default=0, verbose_name='Goles a favor'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje'),
        ),
    ]
