# Generated by Django 4.2.4 on 2023-11-01 13:08

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_output_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de entrada')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Total de productos')),
                ('cost', models.FloatField(validators=[core.models.validate_positive], verbose_name='Costo total')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entrada',
                'ordering': ['id'],
            },
        ),
    ]
