# Generated by Django 4.2.4 on 2023-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_cost_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Campeonato', max_length=30, verbose_name='Nombre'),
        ),
    ]
