# Generated by Django 4.2.4 on 2023-11-01 14:00

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='output_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='output',
            name='car',
        ),
        migrations.AddField(
            model_name='entry',
            name='individual_cost',
            field=models.FloatField(default=0, validators=[core.models.validate_positive], verbose_name='Costo individual'),
        ),
        migrations.AddField(
            model_name='output',
            name='cost',
            field=models.FloatField(default=0, validators=[core.models.validate_positive], verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='output',
            name='individual_cost',
            field=models.FloatField(default=0, validators=[core.models.validate_positive], verbose_name='Costo individual'),
        ),
        migrations.AddField(
            model_name='output',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AddField(
            model_name='output',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de productos'),
        ),
        migrations.AddField(
            model_name='output',
            name='type',
            field=models.CharField(default='inventario', max_length=50, verbose_name='Tipo de salida'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cost',
            field=models.FloatField(default=0, validators=[core.models.validate_positive], verbose_name='Costo total'),
        ),
    ]
