# Generated by Django 4.2.4 on 2023-11-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_output_date_output_date_remove_output_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='individual_cost',
        ),
        migrations.AddField(
            model_name='output',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.car'),
        ),
    ]
