# Generated by Django 4.2.4 on 2023-11-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_output_individual_cost_output_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='individual_cost',
        ),
    ]
