# Generated by Django 4.2.4 on 2023-11-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_entry_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='cost',
        ),
    ]
