# Generated by Django 4.2.4 on 2023-12-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score_admin',
            field=models.BooleanField(default=False, verbose_name='Like de admin'),
        ),
    ]
