# Generated by Django 4.2.4 on 2023-12-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userboli',
            name='buy_cooldown',
            field=models.PositiveIntegerField(default=0, verbose_name='Enfriamiento para comprar'),
        ),
    ]
