# Generated by Django 4.2.4 on 2023-09-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboli',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/', verbose_name='Avatar'),
        ),
    ]
