# Generated by Django 4.2.4 on 2023-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userboli_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboli',
            name='avatar',
            field=models.ImageField(default='avatar_default/exampleUser.png', null=True, upload_to='avatar/', verbose_name='Avatar'),
        ),
    ]
