# Generated by Django 4.2.4 on 2023-09-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userboli_avatar_alter_userboli_birthdate_and_more'),
        ('user', '0003_alter_userboli_avatar'),
    ]

    operations = [
    ]
